version: '2'

services: 
    app:
        build: 
        ports:
            - 
        networks:
            - 

    mysql:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
            -
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - 
        networks:
            -

volumes:
    

networks: 
