version: '2'

services:
    app:
        build: ./app
        ports:
            - 9000:3000
        networks:
            - frontend
            - backend

    mysql:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - data_mysql:/var/lib/mysql
        networks:
            - backend

volumes:
    data_mysql:

networks:
    frontend:
    backend:
